name: software-engineering-lab-9

on:
  push:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r DJANGO/requirements.txt

      - name: Generate API documentation
        run: |
          source venv/bin/activate
          python DJANGO/manage.py generateschema > docs.json

      - name: Commit and push documentation
        run: |
          git config --global user.mail "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add docs.json index.html  
          git commit -m "Updated documentation"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}